### ISSUE TITLE
ADIF from Log4OM doesn't work

### ISSUE THREAD

**Issue by ofadam** [stephenhouser/qso-mapper#3]
Any idea why an exported ADIF from Log4OM wouldn't work? I get "TypeError: qsoMatches is null" in the browser log.

Here's an example entry from my ADIF:

<A_INDEX:1>3 <ANT_AZ:1>0 <ANT_EL:1>0 <BAND:3>20m <CALL:6>GB1MIR <COMMENT:24>QRP via temporary dipole <CONT:2>EU <COUNTRY:7>England <CQZ:2>14 <DISTANCE:7>6504.84 <DXCC:3>223 <EQSL_QSL_RCVD:1>R <EQSL_QSL_SENT:1>R <FREQ:9>14.081389 <GRIDSQUARE:4>IO91 <ITUZ:2>27 <LOTW_QSL_RCVD:1>R <LOTW_QSL_SENT:1>R <MODE:4>MFSK <SUBMODE:3>FT4 <MY_CITY:6>Peoria <MY_CNTY:6>Peoria <MY_STATE:2>IL <MY_COUNTRY:13>United States <MY_CQ_ZONE:1>4 <MY_DXCC:3>291 <MY_GRIDSQUARE:6>EN50ER <MY_ITU_ZONE:1>8 <MY_NAME:10>Adam Gerik <MY_POSTAL_CODE:5>61603 <MY_RIG:12>ICOM IC-7300 <MY_STATE:2>IL <STATION_CALLSIGN:6>KD9NYE <PROGRAMID:7>LOG4OM2 <PROGRAMVERSION:7>2.6.1.0 <QSL_RCVD:1>R <QSL_RCVD_VIA:1>E <QSL_SENT:1>R <QSL_SENT_VIA:1>E <QSO_COMPLETE:1>Y <QSO_DATE:8>20200528 <QSO_DATE_OFF:8>20200528 <SWL:1>N <TIME_OFF:6>213034 <TIME_ON:6>213016 <TX_PWR:1>5 <K_INDEX:1>1 <MY_LAT:7>40.7292 <MY_LON:7>-89.625 <MY_ANTENNA:9>67FT EFHW <QSO_RANDOM:1>Y <SFI:2>68 <APP_L4ONG_SATELLITE_QSO:1>N <APP_L4ONG_CONTEST:1>N <APP_L4ONG_QSO_CONFIRMATIONS:577>[{"CT":"QSL","S":"Requested","R":"Requested","SV":"Electronic","RV":"Electronic"},{"CT":"EQSL","S":"Requested","R":"Requested","SV":"Electronic","RV":"Electronic"},{"CT":"LOTW","S":"Requested","R":"Requested","SV":"Electronic","RV":"Electronic"},{"CT":"QRZCOM","S":"Requested","R":"No","SV":"Electronic","RV":"Electronic"},{"CT":"HAMQTH","S":"Yes","R":"No","SV":"Electronic","RV":"Electronic","SD":"2020-05-28T00:00:00Z"},{"CT":"HRDLOG","S":"Requested","R":"No","SV":"Electronic","RV":"Electronic"},{"CT":"CLUBLOG","S":"Requested","R":"No","SV":"Electronic","RV":"Electronic"}] <APP_L4ONG_QSO_AWARD_REFERENCES:185>[{"AC":"CCC","R":"G*","G":"EUROPE","SUB":[],"GRA":[]},{"AC":"DXCC","R":"223","G":"EU","SUB":[],"GRA":[]},{"AC":"WAC","R":"EU","SUB":[],"GRA":[]},{"AC":"WAZ","R":"14","SUB":[],"GRA":[]}] <EOR>

**Comment by stephenhouser** [comment]
The log file example you pasted is lacking the end of record `<eor>` tags as required by the [ADIF Specification](http://adif.org/adif227.htm). I don't have Log4OM or a system to easily install it on. Is what you pasted a complete ADIF file or just one record from one?

**Comment by stephenhouser** [comment]
Closing old issue.
