### ISSUE TITLE
Failing to parse ADIF when <eoh> is <EOH>

### ISSUE THREAD

**Issue by mbridak** [stephenhouser/qso-mapper#4]
If you tack an 'i' on the end of the match string in adif.js

from:
 var filePartsMatch = cleanAdifData.match(/(.*)\<eoh>(.*)/);

to:
var filePartsMatch = cleanAdifData.match(/(.*)\<eoh>(.*)/i);

that would fix it right up.
Cheers.

**Comment by stephenhouser** [comment]
Wow, I never saw this. Thanks, looks like I got a few PRs to solve it.
