### ISSUE TITLE
Adding the URL for the ADI file

### ISSUE THREAD

**Issue by Mookseberg** [stephenhouser/qso-mapper#7]
Hi Stephen, I am not a programmer but understand HTML, JS and CSS quite well...... but...

I cannot figure out how and where to put the URL code reading the ***.adi file from a server. 

Any help is appreciated.

Jan,  PA2P

**Comment by alexjj** [comment]
If you want to use Stephen's hosted version you can use it like this:
`https://stephenhouser.com/qso-mapper/?url=https://yourdomain.com/folder/log.adi` and it'll pull it in.

**Comment by stephenhouser** [comment]
Suppose this is solved by my managing not to see if for... 2 years. Thanks @alexjj for answering.
